// Owned markers as lineup.js color keys ("SIZE:Color Name", duplicate names
// carry an ordinal suffix like "3M:Brown-2").
// Updated by tapping in the page (copy button) or via Claude Code.
const INVENTORY = [
  "1MC:Apple Green",
  "1MC:Aqua Green",
  "1MC:Coral Pink",
  "1MC:Orange",
  "1MC:Sky Blue",
  "3M:Apricot",
  "3M:Beige",
  "3M:Black",
  "3M:Blue",
  "3M:Brown",
  "3M:Dark Brown",
  "3M:Dark Red",
  "3M:Emerald Green",
  "3M:Fuchsia",
  "3M:Grey",
  "3M:Ivory",
  "3M:Khaki Green",
  "3M:Lavender",
  "3M:Light Blue",
  "3M:Light Green",
  "3M:Light Pink",
  "3M:Navy Blue",
  "3M:Red",
  "3M:Red Wine",
  "3M:Slate Grey",
  "3M:Violet",
  "3M:White",
  "3M:Aqua Green",
  "3M:Coral Pink",
  "5M:Apple Green",
  "5M:Apricot",
  "5M:Aqua Green",
  "5M:Beige",
  "5M:Black",
  "5M:Blue",
  "5M:Coral Pink",
  "5M:Emerald Green",
  "5M:English Green",
  "5M:Fluorescent Orange",
  "5M:Fluorescent Pink",
  "5M:Fluorescent Red",
  "5M:Gold",
  "5M:Green",
  "5M:Ivory",
  "5M:Lavender",
  "5M:Light Orange",
  "5M:Light Pink",
  "5M:Lilac",
  "5M:Ochre",
  "5M:Pink",
  "5M:Red",
  "5M:Sky Blue",
  "5M:Slate Grey",
  "5M:Violet",
  "5M:White",
  "5M:Fluorescent Yellow",
];
