// Generated by scripts/build-lineup.py from scripts/posca-scrape.json + scripts/number-map.json. Do not hand-edit colors.
const LINEUP = [
 {
  "size": "1MR",
  "label": "PC-1MR",
  "tip": "extra fine 0.7 mm",
  "colors": [
   {
    "key": "1MR:Apricot",
    "name": "Apricot",
    "number": "P4",
    "hex": "#f7d674",
    "category": "Pastel"
   },
   {
    "key": "1MR:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "1MR:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "1MR:Glacier Blue",
    "name": "Glacier Blue",
    "number": null,
    "hex": "#69caf8",
    "category": "Pastel"
   },
   {
    "key": "1MR:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "1MR:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "1MR:Lavender",
    "name": "Lavender",
    "number": "P11",
    "hex": "#d8a5f3",
    "category": "Pastel"
   },
   {
    "key": "1MR:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "1MR:Metallic Blue",
    "name": "Metallic Blue",
    "number": "M33",
    "hex": "#5d99ae",
    "category": "Metallic"
   },
   {
    "key": "1MR:Metallic Green",
    "name": "Metallic Green",
    "number": "M6",
    "hex": "#57a499",
    "category": "Metallic"
   },
   {
    "key": "1MR:Metallic Pink",
    "name": "Metallic Pink",
    "number": "M13",
    "hex": "#a56d95",
    "category": "Metallic"
   },
   {
    "key": "1MR:Metallic Red",
    "name": "Metallic Red",
    "number": "M15",
    "hex": "#be6e58",
    "category": "Metallic"
   },
   {
    "key": "1MR:Orange",
    "name": "Orange",
    "number": "4",
    "hex": "#ff5c39",
    "category": "Standard"
   },
   {
    "key": "1MR:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "1MR:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "1MR:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "1MR:Straw Yellow",
    "name": "Straw Yellow",
    "number": "73",
    "hex": "#fbd872",
    "category": "Standard"
   },
   {
    "key": "1MR:Sunshine Yellow",
    "name": "Sunshine Yellow",
    "number": "P2",
    "hex": "#fbfb76",
    "category": "Pastel"
   },
   {
    "key": "1MR:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "1MR:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "1MR:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "1MC",
  "label": "PC-1MC",
  "tip": "fine conical 0.7-1 mm",
  "colors": [
   {
    "key": "1MC:Apricot",
    "name": "Apricot",
    "number": "P4",
    "hex": "#f7d674",
    "category": "Pastel"
   },
   {
    "key": "1MC:Beige",
    "name": "Beige",
    "number": "45",
    "hex": "#f5e1cc",
    "category": "Standard"
   },
   {
    "key": "1MC:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "1MC:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "1MC:Bright Yellow",
    "name": "Bright Yellow",
    "number": "3",
    "hex": "#ff8f1c",
    "category": "Standard"
   },
   {
    "key": "1MC:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "1MC:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "1MC:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "1MC:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "1MC:Ivory",
    "name": "Ivory",
    "number": "46",
    "hex": "#f2eeca",
    "category": "Standard"
   },
   {
    "key": "1MC:Lavender",
    "name": "Lavender",
    "number": "P11",
    "hex": "#d8a5f3",
    "category": "Pastel"
   },
   {
    "key": "1MC:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "1MC:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "1MC:Light Orange",
    "name": "Light Orange",
    "number": "54",
    "hex": "#ffbe9f",
    "category": "Standard"
   },
   {
    "key": "1MC:Light Pink",
    "name": "Light Pink",
    "number": "51",
    "hex": "#eab8e4",
    "category": "Standard"
   },
   {
    "key": "1MC:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "1MC:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "1MC:Red Wine",
    "name": "Red Wine",
    "number": "60",
    "hex": "#b46b7a",
    "category": "Standard"
   },
   {
    "key": "1MC:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "1MC:Slate Grey",
    "name": "Slate Grey",
    "number": "61",
    "hex": "#5b6770",
    "category": "Standard"
   },
   {
    "key": "1MC:Straw Yellow",
    "name": "Straw Yellow",
    "number": "73",
    "hex": "#fbd872",
    "category": "Standard"
   },
   {
    "key": "1MC:Sunshine Yellow",
    "name": "Sunshine Yellow",
    "number": "P2",
    "hex": "#fbfb76",
    "category": "Pastel"
   },
   {
    "key": "1MC:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "1MC:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "1MC:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "3M",
  "label": "PC-3M",
  "tip": "fine 0.9-1.3 mm",
  "colors": [
   {
    "key": "3M:Apple Green",
    "name": "Apple Green",
    "number": "72",
    "hex": "#78be21",
    "category": "Standard"
   },
   {
    "key": "3M:Apricot",
    "name": "Apricot",
    "number": "P4",
    "hex": "#f7d674",
    "category": "Pastel"
   },
   {
    "key": "3M:Beige",
    "name": "Beige",
    "number": "45",
    "hex": "#f5e1cc",
    "category": "Standard"
   },
   {
    "key": "3M:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "3M:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "3M:Bright Yellow",
    "name": "Bright Yellow",
    "number": "3",
    "hex": "#ff8f1c",
    "category": "Standard"
   },
   {
    "key": "3M:Bronze",
    "name": "Bronze",
    "number": "42",
    "hex": "#bb8459",
    "category": "Standard"
   },
   {
    "key": "3M:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "3M:Dark Brown",
    "name": "Dark Brown",
    "number": "22",
    "hex": "#572d2d",
    "category": "Standard"
   },
   {
    "key": "3M:Dark Red",
    "name": "Dark Red",
    "number": "14",
    "hex": "#9d2235",
    "category": "Standard"
   },
   {
    "key": "3M:Emerald Green",
    "name": "Emerald Green",
    "number": "31",
    "hex": "#169387",
    "category": "Standard"
   },
   {
    "key": "3M:Fuchsia",
    "name": "Fuchsia",
    "number": "11",
    "hex": "#991e66",
    "category": "Standard"
   },
   {
    "key": "3M:Glitter Dark Blue",
    "name": "Glitter Dark Blue",
    "number": "G33",
    "hex": "#006caa",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Green",
    "name": "Glitter Green",
    "number": "G6",
    "hex": "#659959",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Light Blue",
    "name": "Glitter Light Blue",
    "number": "G8",
    "hex": "#4694af",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Orange",
    "name": "Glitter Orange",
    "number": "G4",
    "hex": "#c27237",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Pink",
    "name": "Glitter Pink",
    "number": "G13",
    "hex": "#b97e90",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Red",
    "name": "Glitter Red",
    "number": "G15",
    "hex": "#bd6074",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Violet",
    "name": "Glitter Violet",
    "number": "G12",
    "hex": "#725899",
    "category": "Glitter"
   },
   {
    "key": "3M:Glitter Yellow",
    "name": "Glitter Yellow",
    "number": "G2",
    "hex": "#bfb000",
    "category": "Glitter"
   },
   {
    "key": "3M:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "3M:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "3M:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "3M:Ivory",
    "name": "Ivory",
    "number": "46",
    "hex": "#f2eeca",
    "category": "Standard"
   },
   {
    "key": "3M:Khaki Green",
    "name": "Khaki Green",
    "number": "7",
    "hex": "#3e4827",
    "category": "Standard"
   },
   {
    "key": "3M:Lavender",
    "name": "Lavender",
    "number": "P11",
    "hex": "#d8a5f3",
    "category": "Pastel"
   },
   {
    "key": "3M:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "3M:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "3M:Light Orange",
    "name": "Light Orange",
    "number": "54",
    "hex": "#ffbe9f",
    "category": "Standard"
   },
   {
    "key": "3M:Light Pink",
    "name": "Light Pink",
    "number": "51",
    "hex": "#eab8e4",
    "category": "Standard"
   },
   {
    "key": "3M:Lilac",
    "name": "Lilac",
    "number": "34",
    "hex": "#7d55c7",
    "category": "Standard"
   },
   {
    "key": "3M:Navy Blue",
    "name": "Navy Blue",
    "number": "9",
    "hex": "#002b49",
    "category": "Standard"
   },
   {
    "key": "3M:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "3M:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "3M:Red Wine",
    "name": "Red Wine",
    "number": "60",
    "hex": "#b46b7a",
    "category": "Standard"
   },
   {
    "key": "3M:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "3M:Sky Blue",
    "name": "Sky Blue",
    "number": "48",
    "hex": "#009cde",
    "category": "Standard"
   },
   {
    "key": "3M:Slate Grey",
    "name": "Slate Grey",
    "number": "61",
    "hex": "#5b6770",
    "category": "Standard"
   },
   {
    "key": "3M:Sunshine Yellow",
    "name": "Sunshine Yellow",
    "number": "P2",
    "hex": "#fbfb76",
    "category": "Pastel"
   },
   {
    "key": "3M:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "3M:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "3M:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "5M",
  "label": "PC-5M",
  "tip": "medium 1.8-2.5 mm",
  "colors": [
   {
    "key": "5M:Apple Green",
    "name": "Apple Green",
    "number": "72",
    "hex": "#78be21",
    "category": "Standard"
   },
   {
    "key": "5M:Apricot",
    "name": "Apricot",
    "number": "P4",
    "hex": "#f7d674",
    "category": "Pastel"
   },
   {
    "key": "5M:Aqua Green",
    "name": "Aqua Green",
    "number": "P6",
    "hex": "#71dbd4",
    "category": "Pastel"
   },
   {
    "key": "5M:Beige",
    "name": "Beige",
    "number": "45",
    "hex": "#f5e1cc",
    "category": "Standard"
   },
   {
    "key": "5M:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "5M:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "5M:Bright Yellow",
    "name": "Bright Yellow",
    "number": "3",
    "hex": "#ff8f1c",
    "category": "Standard"
   },
   {
    "key": "5M:Bronze",
    "name": "Bronze",
    "number": "42",
    "hex": "#bb8459",
    "category": "Standard"
   },
   {
    "key": "5M:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "5M:Cacao Brown",
    "name": "Cacao Brown",
    "number": "84",
    "hex": "#7c3a2d",
    "category": "Standard"
   },
   {
    "key": "5M:Coral Pink",
    "name": "Coral Pink",
    "number": "66",
    "hex": "#ff8da1",
    "category": "Standard"
   },
   {
    "key": "5M:Deep Grey",
    "name": "Deep Grey",
    "number": "82",
    "hex": "#545859",
    "category": "Standard"
   },
   {
    "key": "5M:Emerald Green",
    "name": "Emerald Green",
    "number": "31",
    "hex": "#169387",
    "category": "Standard"
   },
   {
    "key": "5M:English Green",
    "name": "English Green",
    "number": "83",
    "hex": "#205c40",
    "category": "Standard"
   },
   {
    "key": "5M:Fluorescent Orange",
    "name": "Fluorescent Orange",
    "number": "F4",
    "hex": "#ff7244",
    "category": "Fluo"
   },
   {
    "key": "5M:Fluorescent Pink",
    "name": "Fluorescent Pink",
    "number": "F13",
    "hex": "#ff3eb5",
    "category": "Fluo"
   },
   {
    "key": "5M:Fluorescent Red",
    "name": "Fluorescent Red",
    "number": "F15",
    "hex": "#ff5256",
    "category": "Fluo"
   },
   {
    "key": "5M:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "5M:Grape Green",
    "name": "Grape Green",
    "number": null,
    "hex": "#cace58",
    "category": "Standard"
   },
   {
    "key": "5M:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "5M:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "5M:Ivory",
    "name": "Ivory",
    "number": "46",
    "hex": "#f2eeca",
    "category": "Standard"
   },
   {
    "key": "5M:Lavender",
    "name": "Lavender",
    "number": "P11",
    "hex": "#d8a5f3",
    "category": "Pastel"
   },
   {
    "key": "5M:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "5M:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "5M:Light Orange",
    "name": "Light Orange",
    "number": "54",
    "hex": "#ffbe9f",
    "category": "Standard"
   },
   {
    "key": "5M:Light Pink",
    "name": "Light Pink",
    "number": "51",
    "hex": "#eab8e4",
    "category": "Standard"
   },
   {
    "key": "5M:Lilac",
    "name": "Lilac",
    "number": "34",
    "hex": "#7d55c7",
    "category": "Standard"
   },
   {
    "key": "5M:Metallic Blue",
    "name": "Metallic Blue",
    "number": "M33",
    "hex": "#5d99ae",
    "category": "Metallic"
   },
   {
    "key": "5M:Metallic Green",
    "name": "Metallic Green",
    "number": "M6",
    "hex": "#57a499",
    "category": "Metallic"
   },
   {
    "key": "5M:Metallic Pink",
    "name": "Metallic Pink",
    "number": "M13",
    "hex": "#a56d95",
    "category": "Metallic"
   },
   {
    "key": "5M:Metallic Red",
    "name": "Metallic Red",
    "number": "M15",
    "hex": "#be6e58",
    "category": "Metallic"
   },
   {
    "key": "5M:Metallic Violet",
    "name": "Metallic Violet",
    "number": "M12",
    "hex": "#856ca2",
    "category": "Metallic"
   },
   {
    "key": "5M:Ochre",
    "name": "Ochre",
    "number": "19",
    "hex": "#c69214",
    "category": "Standard"
   },
   {
    "key": "5M:Orange",
    "name": "Orange",
    "number": "4",
    "hex": "#ff5c39",
    "category": "Standard"
   },
   {
    "key": "5M:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "5M:Prussian Blue",
    "name": "Prussian Blue",
    "number": "10",
    "hex": "#330072",
    "category": "Standard"
   },
   {
    "key": "5M:Raspberry",
    "name": "Raspberry",
    "number": "57",
    "hex": "#893b67",
    "category": "Standard"
   },
   {
    "key": "5M:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "5M:Red Wine",
    "name": "Red Wine",
    "number": "60",
    "hex": "#b46b7a",
    "category": "Standard"
   },
   {
    "key": "5M:Ruby Red",
    "name": "Ruby Red",
    "number": "56",
    "hex": "#b7312c",
    "category": "Standard"
   },
   {
    "key": "5M:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "5M:Sky Blue",
    "name": "Sky Blue",
    "number": "48",
    "hex": "#009cde",
    "category": "Standard"
   },
   {
    "key": "5M:Slate Grey",
    "name": "Slate Grey",
    "number": "61",
    "hex": "#5b6770",
    "category": "Standard"
   },
   {
    "key": "5M:Straw Yellow",
    "name": "Straw Yellow",
    "number": "73",
    "hex": "#fbd872",
    "category": "Standard"
   },
   {
    "key": "5M:Sunshine Yellow",
    "name": "Sunshine Yellow",
    "number": "P2",
    "hex": "#fbfb76",
    "category": "Pastel"
   },
   {
    "key": "5M:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "5M:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "5M:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   },
   {
    "key": "5M:Fluorescent Yellow",
    "name": "Fluorescent Yellow",
    "number": "F2",
    "hex": "#ffff2e",
    "category": "Fluo"
   }
  ]
 },
 {
  "size": "5BR",
  "label": "PC-5BR",
  "tip": "brush",
  "colors": [
   {
    "key": "5BR:Beige",
    "name": "Beige",
    "number": "45",
    "hex": "#f5e1cc",
    "category": "Standard"
   },
   {
    "key": "5BR:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "5BR:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "5BR:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "5BR:Coral Pink",
    "name": "Coral Pink",
    "number": "66",
    "hex": "#ff8da1",
    "category": "Standard"
   },
   {
    "key": "5BR:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "5BR:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "5BR:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "5BR:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "5BR:Light Pink",
    "name": "Light Pink",
    "number": "51",
    "hex": "#eab8e4",
    "category": "Standard"
   },
   {
    "key": "5BR:Orange",
    "name": "Orange",
    "number": "4",
    "hex": "#ff5c39",
    "category": "Standard"
   },
   {
    "key": "5BR:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "5BR:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "5BR:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "5BR:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "5BR:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "7M",
  "label": "PC-7M",
  "tip": "broad 4.5-5.5 mm",
  "colors": [
   {
    "key": "7M:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "7M:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "7M:Bright Yellow",
    "name": "Bright Yellow",
    "number": "3",
    "hex": "#ff8f1c",
    "category": "Standard"
   },
   {
    "key": "7M:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "7M:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "7M:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "7M:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "7M:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "7M:Light Orange",
    "name": "Light Orange",
    "number": "54",
    "hex": "#ffbe9f",
    "category": "Standard"
   },
   {
    "key": "7M:Orange",
    "name": "Orange",
    "number": "4",
    "hex": "#ff5c39",
    "category": "Standard"
   },
   {
    "key": "7M:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "7M:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "7M:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "7M:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "7M:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "8K",
  "label": "PC-8K",
  "tip": "chisel 8 mm",
  "colors": [
   {
    "key": "8K:Beige",
    "name": "Beige",
    "number": "45",
    "hex": "#f5e1cc",
    "category": "Standard"
   },
   {
    "key": "8K:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "8K:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "8K:Bright Yellow",
    "name": "Bright Yellow",
    "number": "3",
    "hex": "#ff8f1c",
    "category": "Standard"
   },
   {
    "key": "8K:Bronze",
    "name": "Bronze",
    "number": "42",
    "hex": "#bb8459",
    "category": "Standard"
   },
   {
    "key": "8K:Brown",
    "name": "Brown",
    "number": "21",
    "hex": "#c07d59",
    "category": "Standard"
   },
   {
    "key": "8K:Fluorescent Green",
    "name": "Fluorescent Green",
    "number": "F6",
    "hex": "#00bf6f",
    "category": "Fluo"
   },
   {
    "key": "8K:Fluorescent Orange",
    "name": "Fluorescent Orange",
    "number": "F4",
    "hex": "#ff7244",
    "category": "Fluo"
   },
   {
    "key": "8K:Fluorescent Pink",
    "name": "Fluorescent Pink",
    "number": "F13",
    "hex": "#ff3eb5",
    "category": "Fluo"
   },
   {
    "key": "8K:Fluorescent Red",
    "name": "Fluorescent Red",
    "number": "F15",
    "hex": "#ff5256",
    "category": "Fluo"
   },
   {
    "key": "8K:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "8K:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "8K:Grey",
    "name": "Grey",
    "number": "37",
    "hex": "#97999b",
    "category": "Standard"
   },
   {
    "key": "8K:Ivory",
    "name": "Ivory",
    "number": "46",
    "hex": "#f2eeca",
    "category": "Standard"
   },
   {
    "key": "8K:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "8K:Light Green",
    "name": "Light Green",
    "number": "5",
    "hex": "#80e0a7",
    "category": "Standard"
   },
   {
    "key": "8K:Light Orange",
    "name": "Light Orange",
    "number": "54",
    "hex": "#ffbe9f",
    "category": "Standard"
   },
   {
    "key": "8K:Metallic Blue",
    "name": "Metallic Blue",
    "number": "M33",
    "hex": "#5d99ae",
    "category": "Metallic"
   },
   {
    "key": "8K:Metallic Green",
    "name": "Metallic Green",
    "number": "M6",
    "hex": "#57a499",
    "category": "Metallic"
   },
   {
    "key": "8K:Metallic Pink",
    "name": "Metallic Pink",
    "number": "M13",
    "hex": "#a56d95",
    "category": "Metallic"
   },
   {
    "key": "8K:Metallic Red",
    "name": "Metallic Red",
    "number": "M15",
    "hex": "#be6e58",
    "category": "Metallic"
   },
   {
    "key": "8K:Metallic Violet",
    "name": "Metallic Violet",
    "number": "M12",
    "hex": "#856ca2",
    "category": "Metallic"
   },
   {
    "key": "8K:Orange",
    "name": "Orange",
    "number": "4",
    "hex": "#ff5c39",
    "category": "Standard"
   },
   {
    "key": "8K:Pale Fluorescent Orange",
    "name": "Pale Fluorescent Orange",
    "number": null,
    "hex": "#ffff2e",
    "category": "Fluo"
   },
   {
    "key": "8K:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "8K:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "8K:Red Wine",
    "name": "Red Wine",
    "number": "60",
    "hex": "#b46b7a",
    "category": "Standard"
   },
   {
    "key": "8K:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "8K:Slate Grey",
    "name": "Slate Grey",
    "number": "61",
    "hex": "#5b6770",
    "category": "Standard"
   },
   {
    "key": "8K:Straw Yellow",
    "name": "Straw Yellow",
    "number": "73",
    "hex": "#fbd872",
    "category": "Standard"
   },
   {
    "key": "8K:Violet",
    "name": "Violet",
    "number": "12",
    "hex": "#8246af",
    "category": "Standard"
   },
   {
    "key": "8K:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "8K:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "17K",
  "label": "PC-17K",
  "tip": "extra broad 15 mm",
  "colors": [
   {
    "key": "17K:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "17K:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "17K:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "17K:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "17K:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "17K:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "17K:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "17K:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "17K:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "17K:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 },
 {
  "size": "F350",
  "label": "PCF-350",
  "tip": "brush",
  "colors": [
   {
    "key": "F350:Black",
    "name": "Black",
    "number": "24",
    "hex": "#2d2926",
    "category": "Standard"
   },
   {
    "key": "F350:Blue",
    "name": "Blue",
    "number": "33",
    "hex": "#0072ce",
    "category": "Standard"
   },
   {
    "key": "F350:Gold",
    "name": "Gold",
    "number": "25",
    "hex": "#ba9b37",
    "category": "Standard"
   },
   {
    "key": "F350:Green",
    "name": "Green",
    "number": "6",
    "hex": "#009a44",
    "category": "Standard"
   },
   {
    "key": "F350:Light Blue",
    "name": "Light Blue",
    "number": "8",
    "hex": "#5bc2e7",
    "category": "Standard"
   },
   {
    "key": "F350:Pink",
    "name": "Pink",
    "number": "13",
    "hex": "#f57eb6",
    "category": "Standard"
   },
   {
    "key": "F350:Red",
    "name": "Red",
    "number": "15",
    "hex": "#e03e52",
    "category": "Standard"
   },
   {
    "key": "F350:Silver",
    "name": "Silver",
    "number": "26",
    "hex": "#b9bbbb",
    "category": "Standard"
   },
   {
    "key": "F350:White",
    "name": "White",
    "number": "1",
    "hex": "#ffffff",
    "category": "Standard"
   },
   {
    "key": "F350:Yellow",
    "name": "Yellow",
    "number": "2",
    "hex": "#ffd100",
    "category": "Standard"
   }
  ]
 }
];
