# scripts/build-lineup.py — regenerates lineup.js. Run: uv run --no-project python scripts/build-lineup.py
import json
SIZES = [  # (scrape slug, size key, label, tip)
    ('pc-1mr', '1MR', 'PC-1MR', 'extra fine 0.7 mm'),
    ('pc1-mc', '1MC', 'PC-1MC', 'fine conical 0.7-1 mm'),
    ('pc-3m',  '3M',  'PC-3M',  'fine 0.9-1.3 mm'),
    ('pc-5m',  '5M',  'PC-5M',  'medium 1.8-2.5 mm'),
    ('pc-5br', '5BR', 'PC-5BR', 'brush'),
    ('pc-7m',  '7M',  'PC-7M',  'broad 4.5-5.5 mm'),
    ('pc-8k',  '8K',  'PC-8K',  'chisel 8 mm'),
    ('pc-17k', '17K', 'PC-17K', 'extra broad 15 mm'),
    ('pcf-350','F350','PCF-350','brush'),
]
scrape = json.load(open('scripts/posca-scrape.json'))
numbers = json.load(open('scripts/number-map.json'))

def normalize_name(name):
    """Display-normalize a posca.com color name to consistent Title Case.

    posca.com scrapes some names in ALL CAPS (e.g. 'CACAO BROWN', 'YELLOW
    FLUO') and others already in mixed case (e.g. 'Apple Green'). Per the
    2026-07-23 Round 2 decision, ALL-CAPS names get converted to Title Case;
    names that are already mixed-case are left untouched (str.title() would
    mangle things like 'McSomething', but posca.com has none of those, and
    this only fires when the source name is fully upper-case).
    """
    if name.isupper():
        return name.title()
    return name

# Category overrides for null-numbered colors (2026-07-23, Round 3).
#
# When a color's number is null, category() falls back to name-based
# detection, which defaults to Standard for anything without an obvious
# Glitter/Metallic/Fluorescent cue — wrong for colors that are actually
# Pastel-series. An override is recorded ONLY when BOTH saved independent
# sources agree on a non-Standard category via their section/series
# placement (not the posca.com number, which is null for these):
#
#   - scripts/second-source.html (PoscART PMS chart): flat name/number/hex
#     table; Glacier Blue -> number "P33" (P-prefix = Pastel).
#   - scripts/source-jennyscrayoncollection.html + .jpg (Jenny's Crayon
#     Collection infographic): PC-1MR text lists the 5 colors exclusive to
#     the UK assortment in bold — Apricot(P4), Aqua Green(P6), Glacier
#     Blue, Lavender(P11), Sunshine Yellow(P2). The other 4 are confirmed
#     Pastel-series (P-prefixed) in second-source.html, so Jenny's places
#     Glacier Blue in that same series-grouping even though her own
#     infographic (all 65 non-UK colors) doesn't carry it individually.
#   Both sources -> Pastel.
#
# Checked and REJECTED (fallback Standard stands, no override written):
#   - Coral (5M, 5BR): both sources only have "Coral Pink" (#66, plain
#     number = Standard in both) — no non-Standard agreement either way.
#   - Grape Green (5M): absent from both sources entirely.
#   - Black: absent from second-source.html; Jenny's infographic has it
#     plain (#24, Standard) — only one source has data.
#   - White: plain in both sources (#255 second-source, #1 Jenny's) —
#     both agree, but the agreed category is Standard, so no override.
CATEGORY_OVERRIDES = {
    'glacier blue': 'Pastel',
}

def category(name, number):
    if number:
        pfx = number[0]
        if pfx == 'P': return 'Pastel'
        if pfx == 'F': return 'Fluo'
        if pfx == 'M': return 'Metallic'
        if pfx == 'G': return 'Glitter'
        return 'Standard'
    override = CATEGORY_OVERRIDES.get(name.lower())
    if override: return override
    for p, c in (('Glitter', 'Glitter'), ('Metallic', 'Metallic'), ('Fluorescent', 'Fluo')):
        if name.startswith(p): return c
    if 'fluo' in name.lower(): return 'Fluo'
    return 'Standard'

lineup = []
for slug, size, label, tip in SIZES:
    colors, seen = [], {}
    for hexv, raw_name in scrape[slug]['colors']:
        name = normalize_name(raw_name)
        # posca.com lists some names twice within a size (e.g. Brown in PC-3M);
        # keys stay unique via a deterministic ordinal suffix in scrape order.
        seen[name] = seen.get(name, 0) + 1
        key = f'{size}:{name}' if seen[name] == 1 else f'{size}:{name}-{seen[name]}'
        hexl = hexv.lower()
        if seen[name] == 1:
            num = numbers.get(name.lower())
        else:
            # Second+ occurrence of a duplicated name: only verified when a
            # source explicitly pairs THIS hex to a number (see
            # scripts/number-map.json 'name@hex' keys, e.g. the PC-3M second
            # "Brown" == Dark Brown, hex #572d2d, verified 22 by two
            # independent sources). Otherwise stays name-verbatim, number null.
            num = numbers.get(f'{name.lower()}@{hexl}')
        colors.append({'key': key, 'name': name, 'number': num, 'hex': hexl,
                       'category': category(name, num)})
    lineup.append({'size': size, 'label': label, 'tip': tip, 'colors': colors})

body = json.dumps(lineup, indent=1)
open('lineup.js', 'w').write(
    '// Generated by scripts/build-lineup.py from scripts/posca-scrape.json'
    ' + scripts/number-map.json. Do not hand-edit colors.\n'
    f'const LINEUP = {body};\n')
print('lineup.js written')
